# Generated by Django 4.1 on 2022-11-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=64, verbose_name='USER_UUID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('device', models.CharField(max_length=1000, verbose_name='HTTP_USER_AGENT')),
                ('count', models.IntegerField(default=1, editable=False, verbose_name='REQUEST_COUNT')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
            ],
        ),
    ]
