# Generated by Django 4.2.5 on 2024-11-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=1000, verbose_name='FULL_NAME')),
                ('short_name', models.CharField(max_length=100, verbose_name='SHORT_NAME')),
                ('jif21', models.CharField(max_length=64, verbose_name='JIF21')),
                ('jif22', models.CharField(max_length=64, verbose_name='JIF22')),
                ('jif23', models.CharField(max_length=64, verbose_name='JIF23')),
                ('Category', models.CharField(max_length=1000, verbose_name='CATEGORY')),
                ('issn', models.CharField(max_length=64, verbose_name='ISSN')),
                ('eissn', models.CharField(max_length=64, verbose_name='EISSN')),
            ],
        ),
    ]
