# Generated by Django 4.2.5 on 2024-11-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='Category',
            new_name='category',
        ),
    ]
