# Generated by Django 4.2.5 on 2024-11-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_rename_category_journal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='category',
            field=models.CharField(max_length=500, verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='full_name',
            field=models.CharField(max_length=190, unique=True, verbose_name='FULL_NAME'),
        ),
    ]
