# Generated by Django 4.2.5 on 2024-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_journal_category_alter_journal_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUGJournalRanking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=190, verbose_name='FULL_NAME')),
                ('tier', models.CharField(max_length=64, verbose_name='TIER')),
                ('subject', models.CharField(max_length=100, verbose_name='SUBJECT')),
            ],
        ),
    ]
