# Generated by Django 4.2.5 on 2024-11-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_cugjournalranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cugjournalranking',
            name='tag',
            field=models.CharField(default='', max_length=64, verbose_name='TAG'),
        ),
    ]
