# Generated by Django 4.2.5 on 2023-09-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcParams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='NAME')),
                ('pin', models.CharField(max_length=64, verbose_name='PIN')),
                ('file_path', models.CharField(max_length=1000, verbose_name='FILE_PATH')),
                ('uploader_email', models.EmailField(max_length=64, null=True, verbose_name='UPLOADER_EMAIL')),
            ],
        ),
        migrations.CreateModel(
            name='CalcRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=64, verbose_name='USER_UUID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('device', models.CharField(max_length=1000, verbose_name='HTTP_USER_AGENT')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('file_path', models.CharField(max_length=1000, null=True, verbose_name='FILE_NAME')),
                ('cache_key', models.CharField(max_length=64, null=True, verbose_name='CACHE_KEY')),
            ],
        ),
        migrations.CreateModel(
            name='IrraParams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='NAME')),
                ('pin', models.CharField(max_length=64, verbose_name='PIN')),
                ('file_path', models.CharField(max_length=1000, verbose_name='FILE_PATH')),
                ('uploader_email', models.EmailField(max_length=64, null=True, verbose_name='UPLOADER_EMAIL')),
            ],
        ),
    ]
