# Generated by Django 4.2.5 on 2023-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmpParams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='NAME')),
                ('pin', models.CharField(max_length=64, verbose_name='PIN')),
                ('file_path', models.CharField(max_length=1000, verbose_name='FILE_PATH')),
                ('uploader_email', models.EmailField(max_length=64, null=True, verbose_name='UPLOADER_EMAIL')),
            ],
        ),
    ]
