# Generated by Django 4.2.5 on 2023-10-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_smpparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcparams',
            name='ip',
            field=models.CharField(max_length=64, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='irraparams',
            name='ip',
            field=models.CharField(max_length=64, null=True, verbose_name='IP'),
        ),
    ]
