# Generated by Django 4.2.5 on 2024-01-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_inputfilter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputFilter',
            new_name='InputFilterParams',
        ),
    ]
